# Generated by Django 5.0.6 on 2024-06-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0003_directory_last_modified_directory_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
