# Generated by Django 5.0.6 on 2024-06-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0005_document_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
