# Generated by Django 5.0.6 on 2024-06-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0006_statistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
