# Generated by Django 5.0.6 on 2024-06-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0007_delete_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
